### PR TITLE
Upgrade to RC2

### PR DESCRIPTION
**Pull request by dirkgr**
We originally forked PDFBox 2 some time in September, in the middle of development. We just took whatever their latest master was, and then we complained about it being unstable. By now they've released two release candidates. This one is RC2. I hope that the API is now stable, and the code a bit more reliable.

The merge was a complete disaster because of the way you originally did the renaming. Git couldn't figure out that any of the files in the renamed directories go together. So I just did it over again, without renaming the directory. Instead, I renamed the package name from `org.apache.pdfbox` to `org.allenai.pdfbox`. It took IntelliJ a good 15 minutes of CPU time to do this, but it was almost completely automatic. I'm hoping that this will make the next merge clean. On the plus side, this means that the whole project builds properly (including at the root level). On the minus side, it means that this is not a drop-in replacement for the first version of `pdfbox-ai2`.

@rodneykinney, I don't mean to send all my reviews to you, but invariably you're the one who touched the code last, wherever I look. If you want to spread the load a bit better, let me know, and I'll find alternatives.

### CODE REVIEW

**Comment by rodneykinney** [comment]
LGTM. Sounds like a much better way to create a different namespace than what I tried.

**Comment by dirkgr** [comment]
How did you originally publish this?

**Comment by dirkgr** [comment]
I just uploaded it manually to our nexus.

**Comment by amosjyng** [comment]
Dirk are you ok? Why you talking to yourself?

**Comment by dirkgr** [comment]
It was supposed to mean "Nevermind, I just did it this way. I don't need the answer anymore."

But I like your interpretation!

Are you following all the pull requests?

**Comment by amosjyng** [comment]
Ohh hahaha. That makes a lot more sense.

Apparently I'm watching everything in this repo. Guess I didn't notice before since this doesn't usually change much

**Comment by rodneykinney** [comment]
I also just uploaded it manually.

**Pull request merged**
